spring:
  rabbitmq:
    host: armadillo-01.rmq.cloudamqp.com
    port: 5672
    username: insert username
    password: insert password
  cloud:
    gcp:
      firestore:
        credentials:
          location: classpath:reina-s-base-firebase-adminsdk-gbnda-4c87bdff41.json
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:9000/oauth2/jwks
server:
  tomcat:
    relaxed-query-chars: "{,}, [,]"
